export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO'
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS'
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO'
export const SELECCIONAR_PROYECTO = 'SELECCIONAR_PROYECTO'
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO'
export const MOSTRAR_ERROR_PROYECTO = 'MOSTRAR_ERROR_PROYECTO'

export const TAREAS_PROYECTO = 'TAREAS_PROYECTO'
export const CREAR_TAREA = 'CREAR_TAREA'
export const VALIDAR_TAREA = 'VALIDAR_TAREA'
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA'
export const CAMBIAR_ESTADO_TAREA = 'CAMBIAR_ESTADO_TAREA'
export const SELECCIONAR_TAREA = 'SELECCIONAR_TAREA'
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';